# Generated by Django 3.1 on 2020-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graveyard', '0002_auto_20200819_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
